.TH "DEDB RM" "1" "2026-01-01" "0.1.0" "dedb rm Manual"
.SH NAME
dedb\-rm \- Delete one or more downloaded games' directory trees.
.SH SYNOPSIS
.B dedb rm
[OPTIONS] GAMES...
.SH DESCRIPTION
Delete one or more downloaded games' directory trees.
.PP
GAME are specified as <scheme>:<id> or -b <scheme> <identifier>,
or just <identifier> for downloaded games.
.PP
Shell wildcards (*, ?, [...]) can be matched against downloaded games, e.g. 'gog:tyrian*'.
A bare 'gog:' matches every download under that backend, same as 'gog:*'.
.PP
The user will be prompted for confirmation unless -y is passed.
.SH OPTIONS
.TP
\fB\-b,\fP \-\-backend SCHEME
Read GAME as a bare id for this backend, rather than a <scheme>://<id> URL.
.TP
\fB\-y,\fP \-\-yes
Remove without prompting.
