.TH "DEDB REFRESHMETADATA" "1" "2026-01-01" "0.0.16" "dedb refreshmetadata Manual"
.SH NAME
dedb\-refreshmetadata \- Re-fetch backend metadata for games and rewriting each metadata.json.
.SH SYNOPSIS
.B dedb refreshmetadata
[OPTIONS] [GAMES]...
.SH DESCRIPTION
Re-fetch backend metadata for games and rewriting each metadata.json.
.PP
GAME are specified as <scheme>:<id> or -b <scheme> <identifier>,
or just <identifier> for downloaded games.
.PP
If no games are specified, defaults to all downloaded games.
.PP
Games that have not been downloaded are skipped.
Games that don't exist (can't be resolved) are an error.
.PP
.SH OPTIONS
.TP
\fB\-b,\fP \-\-backend SCHEME
Read GAME as a bare id for this backend, rather than a <scheme>://<id> URL.
