"""Render a markdown table showing how DOSBox conf fields are converted to DOSEMU2 conf fields.

Everything here is read off :mod:`dedb.convert.models` - the
``DosemuConfigFromDosbox`` translation model, cross-referenced with the
``DosboxConfig`` and ``DosemuConfig`` field metadata - so the table in
``ARCHITECTURE.md`` can't drift from the code.

    python -m dedb.convert.fieldmap            # print the table
    python -m dedb.convert.fieldmap --write    # splice it into ARCHITECTURE.md
    python -m dedb.convert.fieldmap --check    # exit 1 if ARCHITECTURE.md is stale
"""

import sys
from dataclasses import dataclass
from pathlib import Path

from pydantic import AliasPath
from pydantic.fields import FieldInfo

from .models import DosboxConfig, DosemuConfig, DosemuConfigFromDosbox

START = "<!-- fieldmap:start (generated by `python -m dedb.convert.fieldmap --write`) -->"
END = "<!-- fieldmap:end -->"


@dataclass(frozen=True)
class Row:
    dosbox: str  # "[section] key" in dosbox.conf
    default: str  # DosboxConfig default, as text
    dosemu: str  # "$_var" in dosemu.conf, or "-" when not translated
    kind: str  # DosemuConfig field type, or "-"
    conversion: str  # one-line gloss


def _dosbox_key(field: FieldInfo) -> str:
    alias = field.validation_alias
    assert isinstance(alias, AliasPath)  # every DosboxConfig setting field has one
    return f"[{alias.path[0]}] {alias.path[-1]}"


def _rows() -> tuple[list[Row], list[Row]]:
    """(translated rows, not-translated rows), from the translation model."""
    dosbox = DosboxConfig.model_fields
    translated: list[Row] = []
    untranslated: list[Row] = []

    for name, field in DosemuConfigFromDosbox.model_fields.items():
        src = dosbox[field.validation_alias]  # validation_alias is the DosboxConfig field name
        if field.exclude:  # an Unsupported field
            untranslated.append(
                Row(_dosbox_key(src), repr(src.default), "-", "-", "not translated")
            )
            continue
        out = DosemuConfig.model_fields[name]
        translated.append(
            Row(
                _dosbox_key(src),
                repr(src.default),
                out.serialization_alias,
                out.annotation.__name__,
                field.description or "copied unchanged",
            )
        )
    return translated, untranslated


def _table(rows: list[Row]) -> str:
    head = "| dosbox.conf | default | dosemu.conf | type | conversion |\n"
    head += "|---|---|---|---|---|\n"
    body = "".join(
        f"| `{r.dosbox}` | `{r.default}` | {f'`{r.dosemu}`' if r.dosemu != '-' else '-'} "
        f"| {r.kind} | {r.conversion} |\n"
        for r in rows
    )
    return head + body


def render_markdown() -> str:
    translated, untranslated = _rows()
    return (
        f"{START}\n\n"
        f"Every DosemuConfig field, and where it comes from in dosbox.conf:\n\n"
        f"{_table(translated)}\n"
        f"Read into DosboxConfig but not translated:\n\n"
        f"{_table(untranslated)}\n"
        f"{END}"
    )


ARCHITECTURE_MD = Path(__file__).resolve().parents[3] / "ARCHITECTURE.md"


def _splice(doc: str, block: str) -> str:
    before, _, rest = doc.partition(START)
    _, _, after = rest.partition(END)
    return f"{before}{block}{after}"


def main(argv: list[str]) -> int:
    block = render_markdown()
    if "--check" in argv:
        current = ARCHITECTURE_MD.read_text()
        if block not in current:
            print(
                "ARCHITECTURE.md field map is stale - run `python -m dedb.convert.fieldmap --write`"
            )
            return 1
        return 0
    if "--write" in argv:
        ARCHITECTURE_MD.write_text(_splice(ARCHITECTURE_MD.read_text(), block))
        print(f"updated {ARCHITECTURE_MD}")
        return 0
    print(block)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
