"""Render the DOSBox -> DOSEMU2 field-map table in ARCHITECTURE.md.

Read off `dedb.convert.models`: the `DosemuConfigFromDosbox` translation
model, cross-referenced with the `DosboxConfig` / `DosemuConfig` field
metadata - so the doc can't drift from the code.

    python -m dedb.convert.fieldmap            # print the table
    python -m dedb.convert.fieldmap --write    # splice it into ARCHITECTURE.md
    python -m dedb.convert.fieldmap --check    # exit 1 if ARCHITECTURE.md is stale
"""

import sys
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

from pydantic.fields import FieldInfo

from .models import DosboxConfig, DosemuConfig, DosemuConfigFromDosbox

START = "<!-- fieldmap:start (generated by `python -m dedb.convert.fieldmap --write`) -->"
END = "<!-- fieldmap:end -->"
COLUMNS = ("dosbox.conf", "default", "dosemu.conf", "type", "conversion")


@dataclass(frozen=True)
class Row:
    """One line of the field map: a DOSBox setting and what it becomes.
    Cells are already markdown - ``as_md`` just joins them."""

    dosbox: str  # `[section] key`
    default: str  # the DosboxConfig default
    dosemu: str  # `$_var`, or "-" when not translated
    type: str  # the DosemuConfig field type, or "-"
    conversion: str  # the one-line gloss, or "not translated"

    @classmethod
    def for_field(cls, name: str, field: FieldInfo) -> "Row":
        """`name`/`field` are a DosemuConfigFromDosbox model field."""
        src = DosboxConfig.model_fields[field.validation_alias]
        section, *_, key = src.validation_alias.path
        dosbox, default = f"`[{section}] {key}`", f"`{src.default!r}`"

        if field.exclude:  # an Unsupported field - read, never emitted
            return cls(dosbox, default, "-", "-", "not translated")

        out = DosemuConfig.model_fields[name]
        return cls(
            dosbox,
            default,
            f"`{out.serialization_alias}`",
            out.annotation.__name__,
            field.description or "copied unchanged",
        )

    @property
    def translated(self) -> bool:
        return self.conversion != "not translated"

    def as_md(self) -> str:
        cells = (self.dosbox, self.default, self.dosemu, self.type, self.conversion)
        return f"| {' | '.join(cells)} |"


def _rows() -> list[Row]:
    return [Row.for_field(name, f) for name, f in DosemuConfigFromDosbox.model_fields.items()]


def _table(rows: Iterable[Row]) -> str:
    header = f"| {' | '.join(COLUMNS)} |"
    divider = "|" + "---|" * len(COLUMNS)
    return "\n".join([header, divider, *(r.as_md() for r in rows)]) + "\n"


def render_markdown() -> str:
    rows = _rows()
    return "\n".join(
        [
            START,
            "",
            "Every DosemuConfig field, and where it comes from in dosbox.conf:",
            "",
            _table(r for r in rows if r.translated),
            "Read into DosboxConfig but not translated:",
            "",
            _table(r for r in rows if not r.translated),
            END,
        ]
    )


ARCHITECTURE_MD = Path(__file__).resolve().parents[3] / "ARCHITECTURE.md"


def _splice(doc: str, block: str) -> str:
    before, _, rest = doc.partition(START)
    _, _, after = rest.partition(END)
    return f"{before}{block}{after}"


def main(argv: list[str]) -> int:
    block = render_markdown()
    if "--check" in argv:
        if block not in ARCHITECTURE_MD.read_text():
            print(
                "ARCHITECTURE.md field map is stale - run `python -m dedb.convert.fieldmap --write`"
            )
            return 1
        return 0
    if "--write" in argv:
        ARCHITECTURE_MD.write_text(_splice(ARCHITECTURE_MD.read_text(), block))
        print(f"updated {ARCHITECTURE_MD}")
        return 0
    print(block)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
