"""Render the DOSBox -> DOSEMU2 field map as a Markdown table.

Everything here is derived from :mod:`dedb.dosbox.models` - ``TRANSLATIONS``,
``UNTRANSLATED_DOSBOX_FIELDS`` and the two models' own field metadata - so
the table in ``ARCHITECTURE.md`` can't drift from the code.

    python -m dedb.dosbox.fieldmap            # print the table
    python -m dedb.dosbox.fieldmap --write    # splice it into ARCHITECTURE.md
    python -m dedb.dosbox.fieldmap --check    # exit 1 if ARCHITECTURE.md is stale
"""

import sys
from dataclasses import dataclass
from pathlib import Path

from pydantic import AliasPath
from pydantic.fields import FieldInfo

from .models import (
    TRANSLATIONS,
    UNTRANSLATED_DOSBOX_FIELDS,
    DosboxConfig,
    DosemuConfig,
    Translation,
)

START = "<!-- fieldmap:start (generated by `python -m dedb.dosbox.fieldmap --write`) -->"
END = "<!-- fieldmap:end -->"


@dataclass(frozen=True)
class Row:
    dosbox: str  # "[section] key" in dosbox.conf
    default: str  # DosboxConfig default, as text
    dosemu: str  # "$_var" in dosemu.conf, or "-" when not translated
    kind: str  # DosemuConfig field type, or "-"
    conversion: str  # one-line gloss


def _dosbox_key(field: FieldInfo) -> str:
    alias = field.validation_alias
    assert isinstance(alias, AliasPath)  # every DosboxConfig field has one
    return f"[{alias.path[0]}] {alias.path[-1]}"


def _default(field: FieldInfo) -> str:
    return repr(field.default)


def _dosemu_kind(name: str) -> str:
    return DosemuConfig.model_fields[name].annotation.__name__


def _conversion(t: Translation) -> str:
    if t.note:
        return t.note
    return "copied unchanged" if t.via is None else t.via.__name__


def translated_rows() -> list[Row]:
    dosbox_fields = DosboxConfig.model_fields
    return [
        Row(
            _dosbox_key(dosbox_fields[t.source]),
            _default(dosbox_fields[t.source]),
            DosemuConfig.model_fields[t.target].serialization_alias,
            _dosemu_kind(t.target),
            _conversion(t),
        )
        for t in TRANSLATIONS
    ]


def untranslated_rows() -> list[Row]:
    dosbox_fields = DosboxConfig.model_fields
    return [
        Row(
            _dosbox_key(dosbox_fields[name]),
            _default(dosbox_fields[name]),
            "-",
            "-",
            "not translated",
        )
        for name in UNTRANSLATED_DOSBOX_FIELDS
    ]


def _table(rows: list[Row]) -> str:
    head = "| dosbox.conf | default | dosemu.conf | type | conversion |\n"
    head += "|---|---|---|---|---|\n"
    body = "".join(
        f"| `{r.dosbox}` | `{r.default}` | {f'`{r.dosemu}`' if r.dosemu != '-' else '-'} "
        f"| {r.kind} | {r.conversion} |\n"
        for r in rows
    )
    return head + body


def render_markdown() -> str:
    return (
        f"{START}\n\n"
        f"**Settings** - every one of DosemuConfig's "
        f"{len(DosemuConfig.model_fields)} fields, and where it comes from in dosbox.conf:\n\n"
        f"{_table(translated_rows())}\n"
        f"**Read into DosboxConfig but not carried across:**\n\n"
        f"{_table(untranslated_rows())}\n"
        f"{END}"
    )


ARCHITECTURE_MD = Path(__file__).resolve().parents[3] / "ARCHITECTURE.md"


def _splice(doc: str, block: str) -> str:
    before, _, rest = doc.partition(START)
    _, _, after = rest.partition(END)
    return f"{before}{block}{after}"


def main(argv: list[str]) -> int:
    block = render_markdown()
    if "--check" in argv:
        current = ARCHITECTURE_MD.read_text()
        if block not in current:
            print(
                "ARCHITECTURE.md field map is stale - run `python -m dedb.dosbox.fieldmap --write`"
            )
            return 1
        return 0
    if "--write" in argv:
        ARCHITECTURE_MD.write_text(_splice(ARCHITECTURE_MD.read_text(), block))
        print(f"updated {ARCHITECTURE_MD}")
        return 0
    print(block)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
